### ISSUE TITLE
What do we do with this case

### ISSUE THREAD

**Issue by Asheboy** [clocklimited/TeaGame#20]
![image](https://cloud.githubusercontent.com/assets/1822529/11812908/89642658-a336-11e5-86d8-39a02226409c.png)

**Comment by vaishal** [comment]
8/9s redraw

**Comment by domharrington** [comment]
:+1:

**Comment by Asheboy** [comment]
This is how we played, so no issue here. I feel this might need to be documented.

**Comment by balaclark** [comment]
joker is always hight so this is pretty obvious
