### ISSUE TITLE
Monday morning joker - exempt all week?

### ISSUE THREAD

**Issue by domharrington** [clocklimited/TeaGame#6]
Can this be back dated to all previously remembered instances of this rare occurrence?

**Comment by benjaminparnell** [comment]
> Can this be back dated

:-1:

**Comment by Asheboy** [comment]
I am :+1: for the rule...not too sure about the retrospective ;)

**Comment by balaclark** [comment]
:-1:

**Comment by vaishal** [comment]
:-1:

**Comment by domharrington** [comment]
:(
