### ISSUE TITLE
"Odd One Out" Rule

### ISSUE THREAD

**Issue by bengourley** [clocklimited/TeaGame#7]
If everyone pulls the same number except for you, you make the tea.

Vote please! cc @Asheboy @vaishal @domharrington @benjaminparnell @balaclark and any other TG regulars.

**Comment by vaishal** [comment]
:+1: What happens if the odd one out pulls a joker/blank card?

**Comment by bengourley** [comment]
Interesting question. I would say whichever event has least probability should prevail.

**Comment by Asheboy** [comment]
Probability of 3 of the same card - 4/52 * 3/51 * 2/50 = 1/5525

Probability of pulling the joker - 1/52.

However, I suggest that a joker should always win.

**Comment by vaishal** [comment]
I agree with @Asheboy.

**Comment by benjaminparnell** [comment]
agree with @Asheboy. Cool rule

**Comment by balaclark** [comment]
:+1: joker always wins

**Comment by domharrington** [comment]
Does this rule only apply when it's an official tea game? i.e. 4 people?

**Comment by Asheboy** [comment]
In my opinion, yes.

**Comment by balaclark** [comment]
Non-official games are not bound by the official rules, the rules can be whatever the players agree to follow.

**Comment by balaclark** [comment]
I count three :+1:s @bengourley want to make a pull request?

**Comment by Asheboy** [comment]
@bengourley Are you able to merge this please? We just has this cause and couldn't use this rule.

**Comment by bengourley** [comment]
I can't merge this as it's an issue :sob:

**Comment by balaclark** [comment]
I now want to rescind my :+1: and am voting :-1:

**Comment by Asheboy** [comment]
That will explain why I can't merge it either.

**Comment by balaclark** [comment]
Closing as already merged in #23
